graph TD
    Input[Input Image: 224x224x3] --> Conv1[Conv 7x7, stride 2]
    Conv1 --> Pool1[Max Pool 3x3, stride 2]
    Pool1 --> Conv2_red[Conv 1x1 reduction]
    Conv2_red --> Conv2[Conv 3x3, stride 1]
    Conv2 --> Pool2[Max Pool 3x3, stride 2]
    
    subgraph Inception_3a
    I3a[Inception 3a]
    end
    Pool2 --> I3a
    
    subgraph Inception_3b
    I3b[Inception 3b]
    end
    I3a --> I3b
    
    I3b --> Pool3[Max Pool 3x3, stride 2]
    
    subgraph Inception_4a_to_4e
    I4[Inception 4a, 4b, 4c, 4d, 4e]
    end
    Pool3 --> I4
    
    I4 --> Pool4[Max Pool 3x3, stride 2]
    
    subgraph Inception_5a_5b
    I5[Inception 5a, 5b]
    end
    Pool4 --> I5
    
    I5 --> AvgPool[Average Pool 7x7, stride 1]
    AvgPool --> Dropout[Dropout 40%]
    Dropout --> FC[Fully Connected / Linear]
    FC --> Softmax[Softmax Output]